
apply plugin: 'java'
apply plugin: 'com.gradleup.shadow'

group 'com.faforever'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    implementation("org.projectlombok:lombok:$lombokVersion")

    implementation("ch.qos.logback:logback-classic:1.5.6")
    implementation("org.slf4j:slf4j-api:2.0.13")

//    implementation project(":ice-adapter")
    implementation(project(":shared"))
    implementation("com.sparkjava:spark-core:2.9.4")
    implementation("com.google.code.gson:gson:$gsonVersion")
}

jar {
    manifest {
        attributes 'Main-Class': 'server.TestServer'
    }
}